### ISSUE TITLE
Add dependabot

### ISSUE THREAD

**Issue by cpaniaguam** [lnccbrown/HSSM#694]
```
# Set update schedule for GitHub Actions

version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every month
      interval: "monthly"
```
